# Generated by Django 2.0.13 on 2019-04-18 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='активност лайка')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='ask.Like'),
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='ask.Like'),
        ),
        migrations.AddField(
            model_name='usr',
            name='likes',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='ask.Like'),
        ),
    ]
