# Generated by Django 2.0.13 on 2019-04-18 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20190418_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usr',
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='ask.Usr'),
        ),
    ]
