# Generated by Django 2.0.13 on 2019-04-15 13:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20190415_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Полное описание ответа')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время создания ответа')),
            ],
        ),
        migrations.AlterField(
            model_name='usr',
            name='upload',
            field=models.ImageField(upload_to='static/ask/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Usr'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Question'),
        ),
    ]
