# Generated by Django 2.0.13 on 2019-04-15 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_auto_20190415_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Question'),
        ),
        migrations.AlterField(
            model_name='usr',
            name='upload',
            field=models.ImageField(upload_to='images/ask/%Y/%m/%d', verbose_name='Ссылка картинки'),
        ),
    ]
