# Generated by Django 2.0.13 on 2019-04-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0007_auto_20190418_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='answers',
        ),
    ]
