# Generated by Django 2.0.13 on 2019-04-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0011_answerlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='answers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Answer'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Question'),
        ),
    ]
